export { default as Register } from './register/Register'
export { default as Login } from './login/Login'
export { default as Home } from './home/Home'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'