export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as Login } from './login/Login'
export { default as Register } from './register/Register'
export { default as Loader } from './loader/Loader'
