--Drop all tables
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS staffs;
DROP TABLE IF EXISTS staff_schedule;
DROP TABLE IF EXISTS schedule;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS bookings;
